[site]
title = "Nima Falaki"
description = "Graduate Research Assistant in Electrical Engineering, focused on Quantum Machine Learning, Artificial Intelligence, and Intelligent Systems."
last_updated = "September 29, 2026"

[author]
name = "Nima Falaki"
title = "Research Assistant"
institution = "Sahand University of Technology"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "nimafalaki1380@gmail.com"

location = ""
location_url = ""
location_details = []

google_scholar = "https://scholar.google.com/citations?user=eOcIzPYAAAAJ&hl=en"

orcid = "https://orcid.org/0009-0000-3348-2083"

github = "https://github.com/Nimafalaki"

linkedin = "https://www.linkedin.com/in/nima-f-ba0075130/"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
mode = "fixed"
fixed_locale = "en"
persist = true
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Projects"
type = "page"
target = "projects"
href = "/projects"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Volunteer Work"
type = "page"
target = "volunteer"
href = "/volunteer"

[[navigation]]
title = "Work Experience"
type = "page"
target = "services"
href = "/services"
[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/Nima_Falaki_CV.pdf"